title: Maniu's Journal
description: Maniu Journal
url: https://journal.maniu.eu

remote_theme: minima
nav_pages:  
  - about.md
  - awesome-gimp.md

site.author.name: Maniu
site.author.email: "me@maniu.eu"

minima:
  social_links:
    - { platform: bluesky, user_url: "https://bsky.app/profile/monkey.maniu.eu" }
    - { platform: instagram, user_url: "https://instagram.com/monkey_maniu" }
